### ISSUE TITLE
Compilation fails because of missing functions

### ISSUE THREAD

**Issue by nilsbore** [ignaciotb/bathymetric_slam#1]
@ignaciotb can you take a look at this?

Discovered by C. Chien:

Scanning dependencies of target gicp_registration
[ 73%] Building CXX object src/registration/CMakeFiles/gicp_registration.dir/src/gicp_reg.cpp.o
/home/chchien/SLAM/bathymetric_slam/src/registration/src/gicp_reg.cpp: In member function ‘double SubmapRegistration::consistencyErrorOverlap(const SubmapObj&, const SubmapObj&)’:
/home/chchien/SLAM/bathymetric_slam/src/registration/src/gicp_reg.cpp:76:76: error: ‘struct benchmark::track_error_benchmark’ has no member named ‘create_grids_from_matrices’
     std::vector<std::vector<std::vector<MatrixXd>>> grid_maps = benchmark_.create_grids_from_matrices(submaps);
                                                                            ^
/home/chchien/SLAM/bathymetric_slam/src/registration/src/gicp_reg.cpp:77:57: error: ‘struct benchmark::track_error_benchmark’ has no member named ‘compute_consistency_error’
     tie(consistency_rms_error, error_vals) = benchmark_.compute_consistency_error(grid_maps);
                                                         ^
src/registration/CMakeFiles/gicp_registration.dir/build.make:62: recipe for target 'src/registration/CMakeFiles/gicp_registration.dir/src/gicp_reg.cpp.o' failed
make[2]: *** [src/registration/CMakeFiles/gicp_registration.dir/src/gicp_reg.cpp.o] Error 1
CMakeFiles/Makefile2:439: recipe for target 'src/registration/CMakeFiles/gicp_registration.dir/all' failed
make[1]: *** [src/registration/CMakeFiles/gicp_registration.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ignaciotb** [comment]
I have to open a PR to AUVLib with the overloaded functions that I'm using for the framework, that's why it fails

**Comment by ignaciotb** [comment]
This should have been fixed now
