### ISSUE TITLE
are missing: auvlib_glad

### ISSUE THREAD

**Issue by chyphen777** [ignaciotb/bathymetric_slam#2]
I am trying to build bathy_metric slam (on uBuntu 16.04).  I have the latest auvlib built and install.  However, I got the following errors during cmake regarding auvlib_glad.   Am I missing anything?   Any suggestion?  Thanks. C. Chien

CMake Error at src/CMakeLists.txt:42 (find_package):
  Found package configuration file:

    /usr/local/share/BathyMaps/cmake/BathyMapsConfig.cmake

  but it set BathyMaps_FOUND to FALSE so package "BathyMaps" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: auvlib_glad

-- Configuring incomplete, errors occurred!

**Comment by ignaciotb** [comment]
Hi Chien, 
I've just added the missing dep for the latest version of AUVlib. Please, try again and close the issue if it's solved.
Regards
