### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by HikariS97** [ignaciotb/bathymetric_slam#5]
/home/krill/BATHY_SLAM_IGNACIOTB/bathymetric_slam/bin/bathy_slam_real --simulation no --bathy_survey real_data/pipeline.cereal"
Input data "real_data/pipeline.cereal"
Number of pings in survey 0
Number of submaps 0
Segmentation fault

pls help, thx :(
(Guess if there's something wrong with memory alignment in Eigen?)

**Comment by ignaciotb** [comment]
The file you're providing seems to be empty (see "Number of pings in survey 0"). You don't seem to be using it the right path.

**Comment by HikariS97** [comment]
If the path wrong, it will print "...  does not exist".
The size of the "pipeline.cereal" have been double checked. It's right.

**Comment by HikariS97** [comment]
I got empty std_pings. Maybe I should check the process in AUVLIB?

**Comment by luxiya01** [comment]
@HikariS97 Sorry for replying to such an old post... The problem could potentially be related to the different versions of AUVLIB. Since the exposed .cereal files are packaged with [https://github.com/ignaciotb/auvlib](https://github.com/ignaciotb/auvlib), you might need to install this specific AUVLIB version to open those data files...

**Comment by lbhqw** [comment]
Hello, we have tried according to what you said, but there are still problems。
l@l:~/bathymetric_slam$ ./bin/bathy_slam_real --simulation no --bathy_survey ./pipeline.cereal --config config.yaml 
Config file: config.yaml
Input data "./pipeline.cereal"
Number of pings in survey 0
Number of submaps 0
Benchmark nbr rows and cols: 200, 1000
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)
已放弃 (核心已转储)
